#! /usr/bin/env bash
JAVA=${JAVA:-java}
_scriptdir=`dirname $0`

usage() {
  _j=${JAR:-$(findJarFile)}
  if [ -z "$_j" ]; then
      echo "Couldn't find the rngdoc2 jar file. Specify using the '-JAR {path-to-jar-file}' command line option."
   else
      $JAVA -jar $_j --help
      cat <<EOF
Additional args include
 -JAR {path-to-rngdoc2-jarfile} specify which rngdoc2 jar file to use
 -v, --verbose          wrapper script verbose output
 -Dlog4j.configurationFile={path-to-log4j2-config-file} 
EOF
  fi
}

findJarFile() {
  for d in . ./target ../../../maven-targets/model-compiler $_scriptdir; do
    for x in $d/rngdoc2-*-jar-with-dependencies.jar $d/rngdoc2*.jar; do
      if [ -f $x ]; then
        echo $x
        return
      fi
    done
  done
  return
}

argv=()
EXTRAJAVAARGS=()
while [ -n "$1" ]; do
  case "$1" in
    -h | --help)
            usage
            exit 1
            ;;
    -JAR)
            JAR=$1
            shift
            ;;
    -v | --verbose)
            verbose=verbose
            ;;
    -D*)
            EXTRAJAVAARGS+=$1
            ;;
    *)
            argv+=($1)
            ;;
  esac
  shift
done

[ -n "$JAR" ] || JAR=`findJarFile`
if [ -z "$JAR" ]; then
  echo "Couldn't find the rngdoc2 jar file. Specify using the '-JAR {path-to-jar-file}' command line option." >&2
  exit 1
fi

_cmd=$(echo $JAVA ${EXTRAJAVAARGS[@]} -jar $JAR ${argv[@]})
[ -n "$verbose" ] && echo $_cmd
$_cmd
